const env = {
  BACKEND_URL: process.env.NEXT_PUBLIC_BACKEND_URL,
  FIREBASE_APIKEY: process.env.NEXT_PUBLIC_FIREBASE_APIKEY,
  PROFANITY_URL: process.env.NEXT_PUBLIC_PROFANITY_URL,
  RECAPTCHA_CLIENT: process.env.NEXT_PUBLIC_RECAPTCHA_CLIENT,
};

export default env;
